# These are supported funding model platforms

github: [aakriti1318]
patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee: aggarwalak
thanks_dev:
custom:
  - https://medium.com/@aakriti-aggarwal
  - https://www.linkedin.com/in/aakritiaggarwal13/
